### PR TITLE
Evaluate if $default is defined instead of using it as a boolean

### PR DESCRIPTION
**Pull request by jlimas**

### CODE REVIEW

**Comment by devinivy** [comment]
Thanks for the contribution!  Could you add a test to ensure we're fixing the case you described in #115?

**Comment by jlimas** [comment]
No worries, really happy to help, I'm a big fan of this library.

**Comment by devinivy** [comment]
Resolves #115

**Comment by Nargonath** [comment]
Thanks @devinivy for the publish and @jlimas for the quick fix. 💪

**Pull request merged**
